# Generated by Django 6.0.6 on 2026-06-13 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_orderitem_product_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='created_at',
            new_name='date',
        ),
    ]
